# Runs tests for opened pull requests under the specific pattern.
name: TypeScript Pull Request Run Tests

on:
  # Allow manual runs
  workflow_dispatch:

  # For testing, run on pushes to typescript patterns
  push:
    paths:
      - "typescript-test-samples/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use all supported nodejs runtimes for lambda
        # https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
        node-version: [14.x,16.x,18.x]

    name: TypeScript ${{ matrix.node-version }} Run Tests

    steps:
      - uses: actions/checkout@v3

      # Figure out which sample we're working with
      # Do this by finding the files that differ between this
      # branch and main (or better: PR target)
      # Every directory under typescript is a candidate for
      # being a sample we need to check
      # git diff finds the files that have changed and saves to a file
      # cat feeds that file into awk
      # awk splits the line by '/' and saves the first segment
      # uniq drops duplicates
      - name: Find Samples
        run: |
          git --no-pager diff --name-only origin/main --output $HOME/changed_files.txt --relative=typescript-test-samples typescript-test-samples
          cat $HOME/changed_files.txt | awk -F '/' '{print($1)}' | uniq > $HOME/changed_patterns.txt
          
      - name: Show files changed
        run: |
          echo "Changed files:\n"
          cat $HOME/changed_files.txt

          echo "Changed patterns:\n"
          cat $HOME/changed_patterns.txt

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Sample Unit Tests
        run: |
          npm run test:unit